### ISSUE TITLE
bingtts.py python 3 compatibility

### ISSUE THREAD

**Issue by elig0n** [westparkcom/Python-Bing-TTS#10]
Python 3 doesn't allow print "" statements but print("") 
2to3 solves it

**Comment by jpattWPC** [comment]
I believe I resolved this issue to where everything works with both 2.x and 3.x

Please test and report back.

**Comment by elig0n** [comment]
I've finished my monthly quota of this TTS engine use so it will take some time until I can report back.

**Comment by elig0n** [comment]
Works fine for me on 2.7.12 and 3.6.2. Compiling reports no error either.

**Comment by jpattWPC** [comment]
There was a type issues with the Authorization header but that's been resolved and tested now.
