### ISSUE TITLE
BadRequestException: 403 Forbidden Issue

### ISSUE THREAD

**Issue by jhoelzl** [westparkcom/Python-Bing-TTS#13]
Hello,

after updating this library from 0.1.1 to 0.1.3, i got this error when using the example in the documentation:

 > File "/myproject/venv/src/bingtts/bingtts/__init__.py", line 201, in speak
    return self.call(headers, "synthesize", body)
  File "/myproject/venv/src/bingtts/bingtts/__init__.py", line 103, in call
    raise BadRequestException(resp)
bingtts.BadRequestException: 403 Forbidden

Is there a possibility to get more detailed information on this error?
I am using Python 3.5.2 on Ubuntu 16.0.4 LTS.

Regards,
Josef

**Comment by jpattWPC** [comment]
You are correct, let me figure out why this is occurring only on Python3.

**Comment by jpattWPC** [comment]
There was a type conversion issue that I didn't foresee, Admittedly I'm only just getting used to Python 3, I have verified that the latest commit fixes this issue.

Please note I renamed the utility that calls the library in order to prevent name conflicts with imports.
