### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by jhoelzl** [westparkcom/Python-Bing-TTS#2]
Hello,

i want to use your library in Python 3.4.3, however, it is not compatible with Python 3.

First, i have changed `httplib` to `http.client`, but then i get another error:
> Can't convert 'bytes' object to str implicitly

Can you help me with that?

Thanks!

**Comment by jhoelzl** [comment]
I changed 

```python
headerfields["Authorization"] = "Bearer " + self.access_token.
```

to 
```python
headerfields["Authorization"] = "Bearer " + self.access_token.decode('utf-8')
```

then it worked. Would be fine, if you could support both Python 2 and 3.
Thanks!

**Comment by jpattWPC** [comment]
I used httplib because the alternatives were giving me a 3-5 second delay in performing the HTTP query, where httplib was instantaneous. If you've got the changes made that make it compatible with Python 3 then please submit a pull request and I'll review and test.

**Comment by jhoelzl** [comment]
I have not realized the 3-5 seconds delay on my system. Anyway, here is the pull request: #3
