### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by rlinke** [westparkcom/Python-Bing-TTS#20]
Thank you for providing the library. However my computer is located behind a HTTP proxy server. I tried several approaches to enable proxy support with the currently employed httplib library but didn't get it to work in any scenario. If you are interested I can share my trials separately.

I added [experimental proxy server support](https://github.com/rlinke/Python-Bing-TTS/commit/0f661727c551178b795159677188cdc16d373572) to this fantastic script. However due to the reason above I switched the underlying httplib library to python3 urllib and python2 urllib2. 

I am unsure about the code quality, I tested the script in both python 2 (2.7.6) and python 3 (3.6.2) and it worked in my manual test cases behind a HTTPS proxy server. I want to test the code without a proxy later.

If you have input on the code or consider the changes as pull request, I would be happy to hear from you.

The code can be found

I forgot to add six library as a dependency in the setup.py script, which I would add before opening a pull request.

**Comment by jpattWPC** [comment]
I seem to recall urllib taking an abnormally long amount of time to load compared to httplib which is why I chose to use that. I primarily use this for telephony so delays need to be minimal.

I will make it a point in the next couple of days to test the load times of urllib vs httplib.

**Comment by jpattWPC** [comment]
I tested importing httplib vs urllib on both python3 and python2.7 and there were not any delays in loading either library. I'm assuming you've tested this library and you've had success so far? If so create a pull request and I'll test.

**Comment by rlinke** [comment]
I made some naive speed [comparison](https://gist.github.com/rlinke/6652b8ff9539b273370ef06b08bd7187) without proxy. 

Because I am currently using the free tier azure service I set it up with sleep limiting.

Tests without proxy worked fine.
I will create a pull request tonight.
