### ISSUE TITLE
How to get "YOURAPIKEYHERE"?

### ISSUE THREAD

**Issue by ernany** [westparkcom/Python-Bing-TTS#4]
How to get "YOURAPIKEYHERE"?

I'm trying for the azure portal >> Text Translator API >> RESOURCE MANAGEMENT >> Keys >> KEY 1

**Comment by jpattWPC** [comment]
Please refer to https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/bingvoiceoutput#Subscription for information about getting an API key.
