### ISSUE TITLE
Suggestion: Add to Readme instructions regarding UTF-8 text

### ISSUE THREAD

**Issue by elig0n** [westparkcom/Python-Bing-TTS#9]
as httplib packet construction caused a problem with my Unicode string, I found out that I have to do this to my text string before I can use it with .speak():

text.encode('utf-8').decode('latin-1') 

This might also apply to other languages so it may be considerate to add it to the README file

**Comment by jpattWPC** [comment]
Do you feel it would it be a good idea to do this in the library itself by default, or just rely on the end-user to perform this conversion?

**Comment by elig0n** [comment]
Under windows  I get this error for every language invocation: 
> python ./bingtts.py --lang=ar-SA,Male --fileformat=riff-8khz-8bit-mono-mulaw --dest=. --cache=. --text="" --apikey
Traceback (most recent call last):
  File "bingtts.py", line 212, in <module>
    m.update(ttsLang + '-' + ttsGender  + '-' + ttsText)
TypeError: Unicode-objects must be encoded before hashing

Under WSL (Ubuntu's bash for windows) English works fine but other languages brings this:
$ python ./bingtts.py --lang=he-IL,Male --fileformat=riff-8khz-8bit-mono-mulaw --dest=a1.wav  --text="Python Kings" --apikey
('Error retrieving speech file:', LanguageException('Invalid language/gender combination: he-IL, Male',))

Although --help shows:
('Language:', 'he-IL', '    Gender:', 'Male')

this is with the updated arrayed namemap

**Comment by jpattWPC** [comment]
Check the commit I made this morning, this should hopefully resolve your issues

**Comment by elig0n** [comment]
I thnk I’ve ran out of quota because I’m receiving 403 Unauthorized when trying to get speech file…
I’ve also sent two pull requests, both deal with utf-8 problems. 
One seems universal because it complains about  non-utf8 hashes (m.update).
The other is a utf8 encode for ttsText.

**Comment by jpattWPC** [comment]
Fixed in your pull request.
